project/metlink/views/metlink.py
from flask import Blueprint, render_template
from metlink import app

metlink = Blueprint('metlink', __name__, template_folder='templates')

@app.route('/<path:path>')
def static_file(path):
    return app.send_static_file(path)
    
@metlink.route('/')    
@metlink.route('/tickets-and-fares/')
def tickets_and_fares():
    
    fare_table = [
                    {"zones": "1", "adult_cash": "$2.00","adult_prepaid": "$1.66", "adult_month": "$49.80","child_cash": "$1.50", "child_prepaid": "$1.24","child_month": "$37.20"}, 
                    {"zones": "2", "adult_cash": "$3.50","adult_prepaid": "$2.73", "adult_month": "$81.90","child_cash": "$2.00", "child_prepaid": "$1.59","child_month": "$47.70"}, 
                    {"zones": "3", "adult_cash": "$5.00","adult_prepaid": "$3.63", "adult_month": "$108.90","child_cash": "$2.50", "child_prepaid": "$1.90","child_month": "$57.00"}, 
                    {"zones": "4", "adult_cash": "$5.50","adult_prepaid": "$4.08", "adult_month": "$122.40","child_cash": "$3.00", "child_prepaid": "$2.33","child_month": "$69.90"}, 
                    {"zones": "5", "adult_cash": "$6.50","adult_prepaid": "$4.98", "adult_month": "$149.40","child_cash": "$3.50", "child_prepaid": "$2.75","child_month": "$82.50"}, 
                    {"zones": "6", "adult_cash": "$8.00","adult_prepaid": "$6.33", "adult_month": "$189.90","child_cash": "$4.00", "child_prepaid": "$3.17","child_month": "$95.10"}, 
                    {"zones": "7", "adult_cash": "$9.00","adult_prepaid": "$7.18", "adult_month": "$215.40","child_cash": "$5.00", "child_prepaid": "$3.64","child_month": "$109.20"}, 
                    {"zones": "8", "adult_cash": "$10.50","adult_prepaid": "$8.03", "adult_month": "$240.90","child_cash": "$5.50", "child_prepaid": "$4.08","child_month": "$122.40"}, 
                    {"zones": "9", "adult_cash": "$11.50","adult_prepaid": "$9.06", "adult_month": "$271.80","child_cash": "$6.00", "child_prepaid": "$4.53","child_month": "$135.90"}, 
                    {"zones": "10", "adult_cash": "$12.50","adult_prepaid": "$9.96", "adult_month": "$298.80","child_cash": "$6.50", "child_prepaid": "$4.98","child_month": "$149.40"}, 
                    {"zones": "11", "adult_cash": "$14.50","adult_prepaid": "$11.40", "adult_month": "$342.00","child_cash": "$7.50", "child_prepaid": "$5.75","child_month": "$172.50"}, 
                    {"zones": "12", "adult_cash": "$15.50","adult_prepaid": "$12.25", "adult_month": "$367.50","child_cash": "$8.00", "child_prepaid": "$6.15","child_month": "$184.50"}, 
                    {"zones": "13", "adult_cash": "$17.00","adult_prepaid": "$13.51", "adult_month": "$405.30","child_cash": "$9.00", "child_prepaid": "$6.75","child_month": "$202.50"}, 
                    {"zones": "14", "adult_cash": "$18.00","adult_prepaid": "$14.40", "adult_month": "$432.00","child_cash": "$9.50", "child_prepaid": "$7.20","child_month": "$216.00"}
                 ]
    
    return render_template('metlink/tickets-and-fares/index.html', fare_table=fare_table)

@metlink.route('/tickets-and-fares/station-lookup/')
def tickets_and_fares_station_lookup():
    return render_template('metlink/tickets-and-fares/station_lookup.html')
    
@metlink.route('/tickets-and-fares/fare-zones/')
def tickets_and_fares_fare_zones():
    return render_template('metlink/tickets-and-fares/fare_zones.html')
    
@metlink.route('/tickets-and-fares/period-passes/')
def tickets_and_fares_period_passes():
    return render_template('metlink/tickets-and-fares/period_passes.html')
 
@metlink.route('/tickets-and-fares/rail-offpeak/')
def tickets_and_fares_rail_offpeak():
    
    fare_table = [
                    {"zones": "1", "adult_cash": "$2.00","adult_cash_offpeak": "$2.00"}, 
                    {"zones": "2", "adult_cash": "$3.50","adult_cash_offpeak": "$3.00"}, 
                    {"zones": "3", "adult_cash": "$5.00","adult_cash_offpeak": "$4.00"}, 
                    {"zones": "4", "adult_cash": "$5.50","adult_cash_offpeak": "$4.50"}, 
                    {"zones": "5", "adult_cash": "$6.50","adult_cash_offpeak": "$5.00"}, 
                    {"zones": "6", "adult_cash": "$8.00","adult_cash_offpeak": "$6.50"}, 
                    {"zones": "7", "adult_cash": "$9.00","adult_cash_offpeak": "$7.50"}, 
                    {"zones": "8", "adult_cash": "$10.50","adult_cash_offpeak": "$8.50"}, 
                    {"zones": "9", "adult_cash": "$11.50","adult_cash_offpeak": "$9.50"}, 
                    {"zones": "10", "adult_cash": "$12.50","adult_cash_offpeak": "$10.00"}, 
                    {"zones": "11", "adult_cash": "$14.50","adult_cash_offpeak": "$14.50"}, 
                    {"zones": "12", "adult_cash": "$15.50","adult_cash_offpeak": "$15.50"}, 
                    {"zones": "13", "adult_cash": "$17.00","adult_cash_offpeak": "$17.00"}, 
                    {"zones": "14", "adult_cash": "$18.00","adult_cash_offpeak": "$18.00"}
                ]
    
    return render_template('metlink/tickets-and-fares/rail_offpeak.html', fare_table=fare_table)
  
@metlink.route('/tickets-and-fares/school-term-passes/')
def tickets_and_fares_school_term():
    
    fare_table = [
                    {"zones": "1", "school_rail": "$95.00","school_mana": "$120.00", "school_classic": "$85.00","school_tranzit": " -"}, 
                    {"zones": "2", "school_rail": "$119.30","school_mana": "$153.00", "school_classic": "$110.00","school_tranzit": "$135.00"}, 
                    {"zones": "3", "school_rail": "$142.50","school_mana": "$183.00", "school_classic": "$140.00","school_tranzit": "$163.00"}, 
                    {"zones": "4", "school_rail": "$174.80","school_mana": "$225.00", "school_classic": "-","school_tranzit": "$199.00"}, 
                    {"zones": "5", "school_rail": "$206.30","school_mana": "$265.00", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "6", "school_rail": "$237.80","school_mana": "$306.00", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "7", "school_rail": "$273.00","school_mana": "$351.00", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "8", "school_rail": "$306.00","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "9", "school_rail": "$339.80","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "10", "school_rail": "$373.50","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "11", "school_rail": "$431.30","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "12", "school_rail": "$461.30","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "13", "school_rail": "$506.30","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "14", "school_rail": "$540.00","school_mana": " -", "school_classic": " -","school_tranzit": " -"}
                ]
    
    return render_template('metlink/tickets-and-fares/school_term.html', fare_table=fare_table)
 
@metlink.route('/tickets-and-fares/transfer-tickets/')
def tickets_and_fares_transfer_tickets():
    return render_template('metlink/tickets-and-fares/transfer_tickets.html')
    
@metlink.route('/tickets-and-fares/other-fares/')
def tickets_and_fares_other_fares():
    return render_template('metlink/tickets-and-fares/other_fares/other_fares.html')
  
@metlink.route('/tickets-and-fares/other-fares/ferry/')
def tickets_and_fares_ferry():
    return render_template('metlink/tickets-and-fares/other_fares/ferry.html')

@metlink.route('/tickets-and-fares/other-fares/airport/')
def tickets_and_fares_airport():
    return render_template('metlink/tickets-and-fares/other_fares/airport.html')
    
@metlink.route('/tickets-and-fares/other-fares/kiwirail-services/')
def tickets_and_fares_kiwirail_services():
    return render_template('metlink/tickets-and-fares/other_fares/kiwirail_services.html')

@metlink.route('/tickets-and-fares/other-fares/cablecar/')
def tickets_and_fares_cablecar():
    return render_template('metlink/tickets-and-fares/other_fares/cablecar.html')

@metlink.route('/tickets-and-fares/other-fares/commuter-buses/')
def tickets_and_fares_commuter_buses():
    return render_template('metlink/tickets-and-fares/other_fares/commuter_buses.html')
  
@metlink.route('/tickets-and-fares/other-fares/after-midnight-buses/')
def tickets_and_fares_after_midnight_buses():
    return render_template('metlink/tickets-and-fares/other_fares/after_midnight_buses.html')
    
@metlink.route('/tickets-and-fares/other-fares/event-tickets/')
def tickets_and_fares_event_tickets():
    return render_template('metlink/tickets-and-fares/other_fares/event_tickets.html')

@metlink.route('/tickets-and-fares/other-fares/supergold/')
def tickets_and_fares_supergold():
    return render_template('metlink/tickets-and-fares/other_fares/supergold.html')
 
  
  
@metlink.route('/tickets-and-fares/how-to-pay-your-fare/')
def tickets_and_fares_how_to_pay_your_fare():
    return render_template('metlink/tickets-and-fares/how_to_pay_your_fare.html')

@metlink.route('/tickets-and-fares/how-to-pay-your-fare/where-to-buy-your-ticket/')
def tickets_and_fares_where_to_buy_your_ticket():
    return render_template('metlink/tickets-and-fares/where_to_buy_your_ticket.html')

@metlink.route('/tickets-and-fares/how-to-pay-your-fare/order-monthly-train-passes/')
def tickets_and_fares_order_monthly_train_passes():
    return render_template('metlink/tickets-and-fares/order_monthly_train_passes.html')
 
  
@metlink.route('/tickets-and-fares/how-to-pay-your-fare/stored-value-cards/')
def tickets_and_fares_stored_value():

project/metlink/templates/metlink/tickets-and-fares/other_fares/after_midnight_buses.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
    
        <div class="page-header">
            <h1>After Midnight buses</h1>
        </div>
        <div class="content">
        
            <p>Use the journey planner to find out which route to use or <a title="after midnight October pdf 2015" href="/assets/New-PDF-timetables/Misc.--Bus-200/After-midnight-October-2015-web.pdf" target="_blank">view the pdf timetable</a>.</p>
            
            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-3">Route</th>
                    <th class="col-md-1">Fare</th>
                    <th class="col-md-3">Description</th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>Routes N1, N2, N3, N4</td>
                    <td>$6.50</td>
                    <td>Metlink Explorer, SuperGold Pass, GO Wellington 30 Day Pass, Hutt Commuter 30 Day Pass and GetAbout 30 Day Pass tickets are accepted. No discount for smartcard.</td>
                </tr>
                <tr>
                    <td>Route N5</td>
                    <td>$6.50</td>
                    <td>Metlink Explorer and SuperGold Pass tickets are accepted. No discount for smartcard.</td>
                </tr>
                <tr>
                    <td>Route N6 within Tawa/Porirua (zones 4 to 6)</td>
                    <td>$6.50</td>
                    <td rowspan="2">Metlink Explorer and SuperGold Pass tickets are accepted. No discount for smartcard.</td>
                </tr>
                <tr>
                    <td>Route N6 from Wellington</td>
                    <td>$13.00</td>
                </tr>
                <tr>
                    <td>N8, N22, N66, N88 within Hutt Valley (zones 4 to 7)</td>
                    <td>$6.50</td>
                    <td rowspan="2">Metlink Explorer, SuperGold Pass, GetAbout 30 Day Pass, and Hutt Commuter 30 Day Pass tickets are accepted. No discount for smartcard.</td>
                </tr>
                <tr>
                    <td>N8, N22, N66, N88 from Wellington</td>
                    <td>$13.00</td>
                </tr>
            </tbody>
            </table>
            
            
            
            
            
            
        </div>
        
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/other_fares/airport.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">

			<div class="page-header">
				<h1>Airport buses</h1>
			</div>

        <div class="content">
        
			<p>There are two bus services that can take passengers to or near the airport.</p>
            <ul>
                <li><a href="http://www.metlink.org.nz/timetables/bus/091" target="_blank">Route 91</a> - Airport Flyer is an express route that travels between Lower Hutt, Wellington City and Airport. See below for <a href="/tickets-and-fares/airport/#R91fares">fare information</a>.</li>
                <li><a href="http://www.metlink.org.nz/timetables/bus/011">Route 11</a> - Seatoun is a regular bus service. It departs from Wellington Station and travels through the city, to Seatoun. It will take you within 10 minutes walk of the airport. Just get off at the corner of Broadway and Hobart Street (Bus Stop Number 6033). This service follows the normal <a href="/tickets-and-fares/" target="_blank">fare</a> structure. For example, if you travel from Wellington Station to the corner of Broadway and Hobart Street (Bus Stop Number 6033) that's 3 zones, and a $5.00 cash fare,</li>
            </ul>
            
            <h3>Airport Flyer fares (route 91)</h3>

            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1">Zones travelled</th>
                    <th class="col-md-1">Adult cash</th>
                    <th class="col-md-1">Adult Snapper</th>
                    <th class="col-md-1">Child cash</th>
                    <th class="col-md-1">Child Snapper</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>1</td><td>$6.00</td><td>$4.80</td><td>$4.00</td><td>$3.20</td></tr>
                <tr><td>2</td><td>$7.00</td><td>$5.60</td><td>$4.50</td><td>$3.60</td></tr>
                <tr><td>3</td><td>$8.00</td><td>$6.40</td><td>$5.00</td><td>$4.00</td></tr>
                <tr><td>4</td><td>$9.00</td><td>$7.20</td><td>$5.50</td><td>$4.40</td></tr>
                <tr><td>5</td><td>$10.00</td><td>$8.00</td><td>$6.00</td><td>$4.80</td></tr>
                <tr><td>6</td><td>$11.00</td><td>$8.80</td><td>$6.50</td><td>$5.20</td></tr>
                <tr><td>7</td><td>$12.00</td><td>$9.60</td><td>$7.00</td><td>$5.60</td></tr>
                <tr><td colspan="5">Passengers travelling to and from the Airport count the Airport stop as another zone. For example: Travelling from Wellington Airport to Wellington city is 4 zones = $9.00 adult cash fare.</td></tr>
            </tbody>
            </table>
            
            <p>Other fare products that can be used on the Airport Flyer are:</p>
            <ul>
                <li><a href="/tickets-and-fares/how-to-pay-your-fare/monthly-passes/#huttcommuter">Hutt Commuter 30 Day Pass</a></li>
                <li><a href="/tickets-and-fares/how-to-pay-your-fare/monthly-passes/#getabout">GetAbout 30 Day Pass</a></li>
                <li><a href="/tickets-and-fares/supergold/">SuperGold</a> card holders - for travel on offpeak services only.</li>
                <li><a href="/tickets-and-fares/how-to-pay-your-fare/day-passes/#explorer">Metlink Explorer ticket</a> - valid after 9.00am on weekdays and all day on weekends and public holidays. </li>
            </ul>
            
        </div>
                        
        
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/other_fares/cablecar.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
    
        <div class="page-header">
            <h1>Cable car</h1>
        </div>
 
       <div class="content">

            <p>The cable car is operated by <a title="Wellington Cable Car New Zealand" href="https://www.wellingtoncablecar.co.nz/" target="_blank">Wellington Cable Car New Zealand</a>. Full up-to-date details on <a title="Cable car fares and ticketing" href="https://www.wellingtoncablecar.co.nz/English/TimetableFares.html" target="_blank">fares and ticketing</a> are available from the cable car website.</p>
       
            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1"></th>
                    <th class="col-md-1">Adult</th>
                    <th class="col-md-1">Child*</th>
                    <th class="col-md-1">Student#</th>
                    <th class="col-md-1">Family^</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>Single cash</td><td>$4.00</td><td>$2.00</td><td>$2.00</td><td>-</td></tr>
                <tr><td>Single Snapper</td><td>$3.50</td><td>-</td><td>-</td><td>-</td></tr>
                <tr><td>Return</td><td>$7.50</td><td>$3.50</td><td>$3.50</td><td>$19.00</td></tr>
                <tr><td>10-trips</td><td>$28.00</td><td>$14.00</td><td>$14.00</td><td>-</td></tr>
                <tr><td>25-trips</td><td>$56.00</td><td>$28.00</td><td>$28.00</td><td>-</td></tr>
                <tr>
                    <td colspan="5">* Child fares are available to children aged 5 to 15. Children under 5 years travel free.</td>
                </tr><tr>
                    <td colspan="5"># Student fares are available to New Zealand full-time tertiary students. Tertiary student ID is required.</td>
                </tr><tr>
                    <td colspan="5">^ Family fares are available for 2 adults and up to 4 children travelling together.</td>
                </tr><tr>
                    <td colspan="5">Full <a title="Cable car fares and ticketing" href="https://www.wellingtoncablecar.co.nz/English/TimetableFares.html" target="_blank">terms and conditions</a> are available on the cable car website.</td>
                </tr>
            </tbody>
            </table>
       
        </div>
        
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/other_fares/commuter_buses.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
    
        <div class="page-header">
            <h1>Commuter buses</h1>
        </div>
 
       <div class="content">
      
            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1"></th>
                    <th class="col-md-1">Adult cash</th>
                    <th class="col-md-1">Adult smartcard</th>
                    <th class="col-md-1">Child cash</th>
                    <th class="col-md-1">Child smartcard</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>Route 80 Wainuiomata Commuter *</td><td>$8.00</td><td>$6.33</td><td>$4.00</td><td>$3.17</td></tr>
                <tr><td>Route 90 Stokes Valley Commuter</td><td>$8.00</td><td>$6.33</td><td>$4.00</td><td>$3.17</td></tr>
                <tr><td>Routes 92, 93 Upper Hutt Commuter buses #</td><td>$9.00</td><td>$7.18</td><td>-</td><td>-</td></tr>
                <tr><td>Route 97 Polytech Link - 2 zones</td><td>$7.00</td><td>$5.65</td><td>-</td><td>-</td></tr>
                <tr><td>Route 97 Polytech Link - 3 zones</td><td>$7.50</td><td>$6.15</td><td>-</td><td>-</td></tr>
                <tr><td>Route 97 Polytech Link - 4 zones</td><td>$8.00</td><td>$6.65</td><td>-</td><td>-</td></tr>
                <tr>
                    <td colspan="5">* Route 80 flat fare of $8.00 for travel between Wainuiomata and Wellington. Zonal fares apply for all other journeys (eg, within Wainuiomata or from Wellington to Gracefield or Petone to Wainuiomata)</td>
                </tr><tr>
                    <td colspan="5"># Route 92 and 93 customers can travel on the Hutt Commuter 30 Day pass. This ticket will allow you to travel not only on Routes 92 and 93* services but also Airport Flyer, Valley Flyer and GO Wellington services.</td>
                </tr>
            </tbody>
            </table>
       
        </div>
        
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/other_fares/event_tickets.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
            
        <div class="page-header">
            <h1>Event tickets</h1>
        </div>
        <div class="content">
            <p>Event tickets are valid for travel on the rail network (excluding Wairarapa line) for selected events only. Additional train services are often provided to manage the extra volume of people.</p> 
            
            <p>Return trip event tickets are available anytime from Metlink ticket offices and agents or on-board staff on event days. Single trip event tickets are available only after an event from the barrier staff at the entrance to the Wellington Railway Station platform.</p>
            
            <p>Event tickets are valid on specified event days and up until 1.15am the following day. For more information call Metlink on 0800 801 700.</p>

            <table class="table">
            <thead>
                <tr><th></th><th>Adult return</th><th>Child return</th><th>Adult single</th><th>Child single</th></tr>
            </thead>
            <tbody>
                <tr><td>Hutt Valley &amp; Kapiti lines</td><td>$12.00</td><td>$6.00</td><td>$6.00</td><td>$3.00</td></tr>
                <tr><td>Johnsonville Line</td><td>$8.00</td><td>$4.00</td><td>$4.00</td><td>$2.00</td></tr>
            </tbody>
            </table>
            
            <h3>Stadium Shuttle</h3>
            <p>These are special GO Wellington shuttle bus services that run during selected events only. The shuttles run between Courtenay Place and Westpac Stadium before and after the events.</p>
            <ul>
                <li>Adult one way - $5.00</li>
                <li>Child one way - $3.00</li>
            </ul>
            <p>SuperGold cards and BusAbout tickets are not accepted. Snapper discount does not apply. GetAbout 30 Day Pass, GO Wellington 30 Day Pass and Metlink Explorer passes are accepted.</p>
            
        </div>
        
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/other_fares/ferry.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
    
        <div class="page-header">
            <h1>Harbour ferry</h1>
        </div>
 
       <div class="content">

            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1"></th>
                    <th class="col-md-3"></th>
                    <th class="col-md-1">Adult</th>
                    <th class="col-md-1">Child*</th>
                    <th class="col-md-1">Student#</th>
                    <th class="col-md-1">Family^</th>
                </tr>
            </thead>
            <tbody>
                <tr><th>Single</th><td>Queens Wharf, Days Bay & Seatoun</td><td>$11.00</td><td>$6.00</td><td>$9.00</td><td>-</td></tr>
                <tr><th rowspan="3">Return</th><td>Queens Wharf, Days Bay & Seatoun</td><td>$22.00</td><td>$12.00</td><td>$18.00</td><td>$61.00</td></tr>
                <tr><td>Matiu Somes Island fares</td><td>$23.00</td><td>$12.00</td><td>$19.00</td><td>$67.00</td></tr>
                <tr><td>Harbour Explorer Excursion</td><td>$22.00</td><td>$12.00</td><td>$18.00</td><td>-</td></tr>
                <tr><th rowspan="2">10-trip</th><td>Queens Wharf and Days Bay</td><td>$87.00</td><td>$37.00</td><td>$61.00</td><td>-</td></tr>
                <tr><td>Seatoun</td><td>$71.00</td><td>$54.00</td><td>-</td><td>-</td></tr>
                <tr><th>Monthly pass</th><td>Queens Wharf, Days Bay & Seatoun</td><td>$270.00</td><td>-</td><td>$199.00</td><td>-</td></tr>
                <tr>
                    <td colspan="6">* Child fares are available to children aged 3 to 15 and to secondary school students aged 16 to 19 in school uniform or whith approved school ID. Children under 3 years travel free.</td>
                </tr><tr>
                    <td colspan="6"># Student fares are available to full-time tertiary students. Tertiary student ID is required.</td>
                </tr><tr>
                    <td colspan="6">^ Family fares are available for 2 adults and up to 4 children travelling together.</td>
                </tr>
            </tbody>
            </table>
       
        </div>
        
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/other_fares/other_fares.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
        <div class="page-header">
            <h1>Other fares</h1>
        </div>
 
       <div class="content">
            <p>The following other fares are also available:</p>
            <ul style="margin-left: 0; padding-left: 0;">
                <li><a href="{{ url_for('metlink.tickets_and_fares_ferry') }}" title="Go to Harbour Ferry page">Harbour Ferry</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_airport') }}" title="Go to Travelling to/from the Airport page">Airport Flyer</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_kiwirail_services') }}" title="Go to KiwiRail services page">Capital Connection</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_cablecar') }}" title="">Cable car</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_commuter_buses') }}" title="Go to Commuter buses page">Commuter buses</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_after_midnight_buses') }}" title="Go to After Midnight buses page">After Midnight buses</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_event_tickets') }}" title="Go to Event Tickets page">Event Tickets</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_supergold') }}" title="Go to Travelling with SuperGold page">Supergold</a></li>
            </ul>
        </div>
        
    </div>


{% endblock %}