project/metlink/views/metlink.py
from flask import Blueprint, render_template
from metlink import app

metlink = Blueprint('metlink', __name__, template_folder='templates')

@app.route('/<path:path>')
def static_file(path):
    return app.send_static_file(path)
    
@metlink.route('/')    
@metlink.route('/tickets-and-fares/')
def tickets_and_fares():
    
    fare_table = [
                    {"zones": "1", "adult_cash": "$2.00","adult_prepaid": "$1.66", "adult_month": "$49.80","child_cash": "$1.50", "child_prepaid": "$1.24","child_month": "$37.20"}, 
                    {"zones": "2", "adult_cash": "$3.50","adult_prepaid": "$2.73", "adult_month": "$81.90","child_cash": "$2.00", "child_prepaid": "$1.59","child_month": "$47.70"}, 
                    {"zones": "3", "adult_cash": "$5.00","adult_prepaid": "$3.63", "adult_month": "$108.90","child_cash": "$2.50", "child_prepaid": "$1.90","child_month": "$57.00"}, 
                    {"zones": "4", "adult_cash": "$5.50","adult_prepaid": "$4.08", "adult_month": "$122.40","child_cash": "$3.00", "child_prepaid": "$2.33","child_month": "$69.90"}, 
                    {"zones": "5", "adult_cash": "$6.50","adult_prepaid": "$4.98", "adult_month": "$149.40","child_cash": "$3.50", "child_prepaid": "$2.75","child_month": "$82.50"}, 
                    {"zones": "6", "adult_cash": "$8.00","adult_prepaid": "$6.33", "adult_month": "$189.90","child_cash": "$4.00", "child_prepaid": "$3.17","child_month": "$95.10"}, 
                    {"zones": "7", "adult_cash": "$9.00","adult_prepaid": "$7.18", "adult_month": "$215.40","child_cash": "$5.00", "child_prepaid": "$3.64","child_month": "$109.20"}, 
                    {"zones": "8", "adult_cash": "$10.50","adult_prepaid": "$8.03", "adult_month": "$240.90","child_cash": "$5.50", "child_prepaid": "$4.08","child_month": "$122.40"}, 
                    {"zones": "9", "adult_cash": "$11.50","adult_prepaid": "$9.06", "adult_month": "$271.80","child_cash": "$6.00", "child_prepaid": "$4.53","child_month": "$135.90"}, 
                    {"zones": "10", "adult_cash": "$12.50","adult_prepaid": "$9.96", "adult_month": "$298.80","child_cash": "$6.50", "child_prepaid": "$4.98","child_month": "$149.40"}, 
                    {"zones": "11", "adult_cash": "$14.50","adult_prepaid": "$11.40", "adult_month": "$342.00","child_cash": "$7.50", "child_prepaid": "$5.75","child_month": "$172.50"}, 
                    {"zones": "12", "adult_cash": "$15.50","adult_prepaid": "$12.25", "adult_month": "$367.50","child_cash": "$8.00", "child_prepaid": "$6.15","child_month": "$184.50"}, 
                    {"zones": "13", "adult_cash": "$17.00","adult_prepaid": "$13.51", "adult_month": "$405.30","child_cash": "$9.00", "child_prepaid": "$6.75","child_month": "$202.50"}, 
                    {"zones": "14", "adult_cash": "$18.00","adult_prepaid": "$14.40", "adult_month": "$432.00","child_cash": "$9.50", "child_prepaid": "$7.20","child_month": "$216.00"}
                 ]
    
    return render_template('metlink/tickets-and-fares/index.html', fare_table=fare_table)

@metlink.route('/tickets-and-fares/station-lookup/')
def tickets_and_fares_station_lookup():
    return render_template('metlink/tickets-and-fares/station_lookup.html')
    
@metlink.route('/tickets-and-fares/fare-zones/')
def tickets_and_fares_fare_zones():
    return render_template('metlink/tickets-and-fares/fare_zones.html')
    
@metlink.route('/tickets-and-fares/period-passes/')
def tickets_and_fares_period_passes():
    return render_template('metlink/tickets-and-fares/period_passes.html')
 
@metlink.route('/tickets-and-fares/rail-offpeak/')
def tickets_and_fares_rail_offpeak():
    
    fare_table = [
                    {"zones": "1", "adult_cash": "$2.00","adult_cash_offpeak": "$2.00"}, 
                    {"zones": "2", "adult_cash": "$3.50","adult_cash_offpeak": "$3.00"}, 
                    {"zones": "3", "adult_cash": "$5.00","adult_cash_offpeak": "$4.00"}, 
                    {"zones": "4", "adult_cash": "$5.50","adult_cash_offpeak": "$4.50"}, 
                    {"zones": "5", "adult_cash": "$6.50","adult_cash_offpeak": "$5.00"}, 
                    {"zones": "6", "adult_cash": "$8.00","adult_cash_offpeak": "$6.50"}, 
                    {"zones": "7", "adult_cash": "$9.00","adult_cash_offpeak": "$7.50"}, 
                    {"zones": "8", "adult_cash": "$10.50","adult_cash_offpeak": "$8.50"}, 
                    {"zones": "9", "adult_cash": "$11.50","adult_cash_offpeak": "$9.50"}, 
                    {"zones": "10", "adult_cash": "$12.50","adult_cash_offpeak": "$10.00"}, 
                    {"zones": "11", "adult_cash": "$14.50","adult_cash_offpeak": "$14.50"}, 
                    {"zones": "12", "adult_cash": "$15.50","adult_cash_offpeak": "$15.50"}, 
                    {"zones": "13", "adult_cash": "$17.00","adult_cash_offpeak": "$17.00"}, 
                    {"zones": "14", "adult_cash": "$18.00","adult_cash_offpeak": "$18.00"}
                ]
    
    return render_template('metlink/tickets-and-fares/rail_offpeak.html', fare_table=fare_table)
  
@metlink.route('/tickets-and-fares/school-term-passes/')
def tickets_and_fares_school_term():
    
    fare_table = [
                    {"zones": "1", "school_rail": "$95.00","school_mana": "$120.00", "school_classic": "$85.00","school_tranzit": " -"}, 
                    {"zones": "2", "school_rail": "$119.30","school_mana": "$153.00", "school_classic": "$110.00","school_tranzit": "$135.00"}, 
                    {"zones": "3", "school_rail": "$142.50","school_mana": "$183.00", "school_classic": "$140.00","school_tranzit": "$163.00"}, 
                    {"zones": "4", "school_rail": "$174.80","school_mana": "$225.00", "school_classic": "-","school_tranzit": "$199.00"}, 
                    {"zones": "5", "school_rail": "$206.30","school_mana": "$265.00", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "6", "school_rail": "$237.80","school_mana": "$306.00", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "7", "school_rail": "$273.00","school_mana": "$351.00", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "8", "school_rail": "$306.00","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "9", "school_rail": "$339.80","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "10", "school_rail": "$373.50","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "11", "school_rail": "$431.30","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "12", "school_rail": "$461.30","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "13", "school_rail": "$506.30","school_mana": " -", "school_classic": " -","school_tranzit": " -"}, 
                    {"zones": "14", "school_rail": "$540.00","school_mana": " -", "school_classic": " -","school_tranzit": " -"}
                ]
    
    return render_template('metlink/tickets-and-fares/school_term.html', fare_table=fare_table)
 
@metlink.route('/tickets-and-fares/transfer-tickets/')
def tickets_and_fares_transfer_tickets():
    return render_template('metlink/tickets-and-fares/transfer_tickets.html')
    
@metlink.route('/tickets-and-fares/other-fares/')
def tickets_and_fares_other_fares():
    return render_template('metlink/tickets-and-fares/other_fares/other_fares.html')
  
@metlink.route('/tickets-and-fares/other-fares/ferry/')
def tickets_and_fares_ferry():
    return render_template('metlink/tickets-and-fares/other_fares/ferry.html')

@metlink.route('/tickets-and-fares/other-fares/airport/')
def tickets_and_fares_airport():
    return render_template('metlink/tickets-and-fares/other_fares/airport.html')
    
@metlink.route('/tickets-and-fares/other-fares/kiwirail-services/')
def tickets_and_fares_kiwirail_services():
    return render_template('metlink/tickets-and-fares/other_fares/kiwirail_services.html')

@metlink.route('/tickets-and-fares/other-fares/cablecar/')
def tickets_and_fares_cablecar():
    return render_template('metlink/tickets-and-fares/other_fares/cablecar.html')

@metlink.route('/tickets-and-fares/other-fares/commuter-buses/')
def tickets_and_fares_commuter_buses():
    return render_template('metlink/tickets-and-fares/other_fares/commuter_buses.html')
  
@metlink.route('/tickets-and-fares/other-fares/after-midnight-buses/')
def tickets_and_fares_after_midnight_buses():
    return render_template('metlink/tickets-and-fares/other_fares/after_midnight_buses.html')
    
@metlink.route('/tickets-and-fares/other-fares/event-tickets/')
def tickets_and_fares_event_tickets():
    return render_template('metlink/tickets-and-fares/other_fares/event_tickets.html')

@metlink.route('/tickets-and-fares/other-fares/supergold/')
def tickets_and_fares_supergold():
    return render_template('metlink/tickets-and-fares/other_fares/supergold.html')
 
  
  
@metlink.route('/tickets-and-fares/how-to-pay-your-fare/')
def tickets_and_fares_how_to_pay_your_fare():
    return render_template('metlink/tickets-and-fares/how_to_pay_your_fare.html')

@metlink.route('/tickets-and-fares/how-to-pay-your-fare/where-to-buy-your-ticket/')
def tickets_and_fares_where_to_buy_your_ticket():
    return render_template('metlink/tickets-and-fares/where_to_buy_your_ticket.html')

@metlink.route('/tickets-and-fares/how-to-pay-your-fare/order-monthly-train-passes/')
def tickets_and_fares_order_monthly_train_passes():
    return render_template('metlink/tickets-and-fares/order_monthly_train_passes.html')
 
  
@metlink.route('/tickets-and-fares/how-to-pay-your-fare/stored-value-cards/')
def tickets_and_fares_stored_value():

project/metlink/templates/metlink/tickets-and-fares/base.html
{% extends "metlink/base.html" %}

{% block nav %} 

<div class="row hasImage">
    <div class="col-xs-12 col-sm-4 col-md-3 subNavHolder">
        <div class="sidebar panel panel-primary">
            <div class="panel-heading">
                <h3>
                    <a class="panel-toggle pull-right visible-xs" data-toggle="collapse" data-parent=".panel-primary" href="{{ url_for('metlink.tickets_and_fares') }}#panel-body-id">
                        <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"> </span>
                    </a>
                    <a href="{{ url_for('metlink.tickets_and_fares') }}">Tickets and fares</a>
                </h3>
            </div>
            <div class="panel-body collapse in" id="panel-body-id">
                <ul id="SubNav" class="navigation list-group">
                    <li class="link list-group-item">
                        <a href="{{ url_for('metlink.tickets_and_fares') }}" title="Tickets and fares">Standard fares</a>
                        <ul class="list-group">
                            <li class="list-group-item link first"><a href="{{ url_for('metlink.tickets_and_fares') }}" title="">Fare schedule</a></li>
                            <li class="list-group-item link"><a href="{{ url_for('metlink.tickets_and_fares_fare_zones') }}" title="Go to Fare zones page">Fare zones</a></li>
                            <li class="list-group-item link"><a href="{{ url_for('metlink.tickets_and_fares_rail_offpeak') }}" title="">Rail off-peak</a></li>
                            <li class="list-group-item link"><a href="{{ url_for('metlink.tickets_and_fares_school_term') }}" title="Go to School Term Passes page">School Term</a></li>                          
                            <li class="list-group-item link "><a href="{{ url_for('metlink.tickets_and_fares_period_passes') }}" title="Go to Period Passes page">Period passes</a></li> 
                            <li class="list-group-item link"><a href="{{ url_for('metlink.tickets_and_fares_transfer_tickets') }}" title="transfer tickets ">Transfer tickets</a></li>
                            <li class="list-group-item link last"><a href="{{ url_for('metlink.tickets_and_fares_station_lookup') }}" title="station lookup">Station lookup</a></li>
                        </ul>
                    </li>
                    <li class="link list-group-item">
                        <a href="{{ url_for('metlink.tickets_and_fares_other_fares') }}" title="Go to Other fares page">Other fares</a>
                        <ul class="list-group">
                            <li class="list-group-item link first"><a href="{{ url_for('metlink.tickets_and_fares_ferry') }}" title="Go to Harbour Ferry page">Harbour ferry</a></li>
                            <li class="list-group-item link"><a href="{{ url_for('metlink.tickets_and_fares_airport') }}" title="Go to Travelling to/from the Airport page">Airport buses</a></li>
                            <li class="list-group-item link last"><a href="{{ url_for('metlink.tickets_and_fares_other_fares') }}" title="Other fares">Other</a></li>
                        </ul>                        
                    </li>
                    <li class="link list-group-item">
                        <a href="{{ url_for('metlink.tickets_and_fares_how_to_pay_your_fare') }}" title="Go to How to pay your fare page">How to pay your fare</a>
                        <ul class="list-group">
                            <li class="list-group-item link first"><a href="{{ url_for('metlink.tickets_and_fares_where_to_buy_your_ticket') }}" title="Go to Where to buy your ticket page">Where to buy your ticket</a></li>
                            <li class="list-group-item link "><a href="{{ url_for('metlink.tickets_and_fares_order_monthly_train_passes') }}" title="Go to Order Monthly Train Passes page">Order monthly pass online</a></li>
                            <li class="list-group-item link last"><a href="{{ url_for('metlink.tickets_and_fares_stored_value') }}" title="Go to Stored value cards page">Stored value cards</a></li>
                        </ul>
                    </li>
                    <li class="link list-group-item">
                        <a href="{{ url_for('metlink.tickets_and_fares_fare_manual') }}" title="">Fare rules</a>
                        <ul class="list-group">
                            <li class="list-group-item link first"><a href="{{ url_for('metlink.tickets_and_fares_new_look_fares') }}" title="Go to New look tickets page">New look tickets</a></li>
                            <li class="list-group-item link"><a href="{{ url_for('metlink.tickets_and_fares_changes_to_some_of_our_train_tickets') }}" title="Go to Changes to some of our train tickets page">Changes to some of our train tickets</a></li>
                            <li class="list-group-item link last"><a href="{{ url_for('metlink.tickets_and_fares_conditions_of_travel') }}" title="Go to Conditions of Carriage page">Conditions of Carriage</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/fare_rules.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
        <div class="page-header">
            <h1>Fare rules</h1>
        </div>
 
       <div class="content">
            
            <p>A detailed specification of fare rules will be available shortly for download.</p>

            <p>Changes to fare products:</p>
            <ul style="margin-left: 0; padding-left: 0;">
                <li><a href="{{ url_for('metlink.tickets_and_fares_new_look_fares') }}" title="Go to New look tickets page">New look tickets</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_changes_to_some_of_our_train_tickets') }}" title="Go to Changes to some of our train tickets page">Changes to some of our train tickets</a></li>
                <li><a href="{{ url_for('metlink.tickets_and_fares_conditions_of_travel') }}" title="Go to Conditions of Carriage page">Conditions of Carriage</a></li>
            </ul>
        </div>
        
    </div>

{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/how_to_pay_your_fare.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
        <div class="page-header">
            <h1>Tickets and fares</h1>
        </div>

        <div class="content">

        <h2>How to pay your fare</h2>
        
        
        <table class="table">
            <thead>
                <tr>
                    <th class="col-md-3">Fare type</th>
                    <th class="col-md-3">Bus</th>
                    <th class="col-md-3">Train</th>
                    <th class="col-md-3">Ferry</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Single cash fares</td>
                    <td>Before boarding have your cash ready to give to the driver. Correct change is appreciated, though small change can be given.</td>
                    <td>Have your cash fare ready to give to the train staff as they move through the train. Correct change is appreciated, though small change can be given. Single cash fares can also be purchased from a ticket office before you board the train.</td>
                    <td rowspan="6">Single cash fares, return fares, 10-trip tickets and monthly passes can be bought using cash or eftpos from on-board staff as they make their way around the Harbour Ferry.  Alternatively tickets can be purchased from the East by West office in Wellington, near the mooring (1 Queens Wharf, Wellington, 6011).</td>
                </tr>
                <tr>
                    <td>Stored Value Cards</td>
                    <td>These can be purchased from the appropriate operator’s ticket agencies, selected bus depots or in some instances from their website or selected bus drivers. When you board the bus hold the card up to the scanner or put it on the machine. Snapper cards also require you to tag off as you leave the bus.</td>
                    <td>NA</td>
                </tr>
                <tr>
                    <td>10-trip tickets</td>
                    <td>NA</td>
                    <td>These tickets can be bought from the train stations and ticket agents.</td>
                </tr>
                <tr>
                    <td>Monthly passes</td>
                    <td>These passes are only available from the relevant bus depot or ticket agencies. You need to tag on or show your pass each time you board the bus.</td>
                    <td>These passes can be purchased from Metlink stations and ticket agents or online. You need to show your pass each time you travel as train staff pass through the train.</td>
                </tr>
                <tr>
                    <td>Day passes</td>
                    <td>These passes can be purchased from the driver. Each time you board you need to show the driver your pass.</td>
                    <td>These passes can be purchased from the on-board train staff or from a ticket office before you board the train.  You need to show your pass each time you travel as train staff pass through the train.</td>
                </tr>
                <tr>
                    <td>Wairarapa trains</td>
                    <td>NA</td>
                    <td>A minimum adult cash fare of $10.50 applies for journeys from Wellington to Petone, Waterloo and Upper Hutt stations on Wairarapa trains.  Waterloo or Petone 10-trip or monthly pass holders must pay a $5.00 cash surcharge, Upper Hutt 10-trip or monthly pass holders must pay a $1.00 cash surcharge. The minimum fare does not apply to Wellington-bound services.</td>
                </tr>

                </tbody>
            </table>
        
            <h2>Other ways we can help:</h2>
            <ul>
                <li>The <a class="ss-broken" href="https://www.metlink.org.nz/##plan">Journey Planner</a> can calculate your cash fare and also plan your trip</li>
                <li>Call the Metlink information line on 04 801 7000 or 0800 801 700</li>
                <li>Email <a href="mailto:info@metlink.org.nz">info@metlink.org.nz</a></li>
                <li>Follow us on&nbsp;Twitter <a title="Metlink Twitter account" href="https://twitter.com/metlinkwgtn" target="_blank">@metlinkwgtn</a>&nbsp;</li>
            </ul>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
       </div>
    </div>
</div>


{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/index.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
        <div class="page-header">
            <h1>Tickets and fares</h1>
        </div>

        <div class="content">

            <h2>Standard fares<a name="fares" class="anchor"></a></h2>
            
            <p>Wellington fares are based on a  <a title="fare zones" href="{{ url_for('metlink.tickets_and_fares_fare_zones') }}">zone system</a>. The fare you pay is based on how many zones you travel through. Just count the number of zone you will travel through, including the ones you will start and finish your journey in.</p>

            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1">Zones<br/>travelled</th>
                    <th class="col-md-1">Adult<br/>Cash</th>
                    <th class="col-md-1">Adult<br/>Prepaid #</th>
                    <th class="col-md-1">Adult<br/>Monthly ^</th>
                    <th class="col-md-1">Child<br/>Cash</th>
                    <th class="col-md-1">Child<br/>Prepaid #</th>
                    <th class="col-md-1">Child<br/>Monthly ^</th>
                </tr>
            </thead>
            <tbody>
                {% for zone in fare_table %}
                    <tr>
                        <td>{{ zone.zones }}</td>
                        <td>{{ zone.adult_cash }}</td>
                        <td>{{ zone.adult_prepaid }}</td>
                        <td>{{ zone.adult_month }}</td>
                        <td>{{ zone.child_cash }}</td>
                        <td>{{ zone.child_prepaid }}</td>
                        <td>{{ zone.child_month }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="7">* Child fares are available to children aged 5 to 15 and to secondary school students in school uniform or whith approved school ID. Children under 5 years travel free.</td>
                </tr>
                <tr>
                    <td colspan="7"># Prepaid fares include smartcard (Snapper) and rail 10-trip (priced at 10x fare shown).</td>
                </tr>
                <tr>
                    <td colspan="7">^ Monthy passes are only available on rail.</td>
                </tr>
                <tr>
                    <td colspan="7">Journeys requiring a change of vehicle will usually require an additional fare, unless you are using a <a title="transfer tickets" href="/tickets-and-fares/transfer-tickets/">transfer ticket</a> or <a title="period passes" href="/tickets-and-fares/period-passes/">period pass</a> that allows transfers.</td>
                </tr>
                <tr>
                    <td colspan="7">GO Wellington bus services have a 3 zone maximum fare.</td>
                </tr>
            </tbody>
            </table>
            
   
       </div>
    </div>
</div>


{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/rail_offpeak.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
        <div class="page-header">
            <h1>Tickets and fares</h1>
        </div>

        <div class="content">

            <h2>Rail off-peak fares<a name="fares" class="anchor"></a></h2>
            
            <p>Wellington fares are based on a  <a title="fare zones" href="{{ url_for('metlink.tickets_and_fares_fare_zones') }}">zone system</a>. The fare you pay is based on how many zones you travel through. Just count the number of zone you will travel through, including the ones you will start and finish your journey in.</p>

            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1">Zones<br/>travelled</th>
                    <th class="col-md-1">Adult cash<br/>peak</th>
                    <th class="col-md-1">Adult cash<br/>off-peak</th>
                </tr>
            </thead>
            <tbody>
                {% for zone in fare_table %}
                    <tr>
                        <td>{{ zone.zones }}</td>
                        <td>{{ zone.adult_cash }}</td>
                        <td>{{ zone.adult_cash_offpeak }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="7">Offpeak fares are only available on rail on specified services. There are no Child off-peak fares.</td>
                </tr>
               
            </tbody>
            </table>
            
       </div>
    </div>
</div>


{% endblock %}

project/metlink/templates/metlink/tickets-and-fares/school_term.html
{% extends "metlink/tickets-and-fares/base.html" %}

{% block main_content %} 
    
    <div id="main" role="main" class="col-xs-12 col-sm-8 col-md-9 col-lg-7 contentHolder">
        <div class="page-header">
            <h1>Tickets and fares</h1>
        </div>

        <div class="content">

            <h2>School term pases<a name="school term" class="anchor"></a></h2>
            
            <p>School term passes are based on the <a title="fare zones" href="{{ url_for('metlink.tickets_and_fares_fare_zones') }}">number of zones travelled</a> and are available on rail and some bus services for child travelling between home and school. To find out what school bus you need to take and who it is operated by, use the journey planner (remember to select "school bus") or click on the magnify glass at the top of the page and search on your school's name. School students without a pass are required to pay a <a title="fares and tickets" href="{{ url_for('metlink.tickets_and_fares') }}">child fare</a>. </p>
            
            <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1">Zones<br/>travelled</th>
                    <th class="col-md-1">Rail#</th>
                    <th class="col-md-1">Mana/ Newlands*</th>
                    <th class="col-md-1">Classic Coaches*</th>
                    <th class="col-md-1">Tranzit*</th>
                </tr>
            </thead>
            <tbody>
                {% for zone in fare_table %}
                    <tr>
                        <td>{{ zone.zones }}</td>
                        <td>{{ zone.school_rail }}</td>
                        <td>{{ zone.school_mana }}</td>
                        <td>{{ zone.school_classic }}</td>
                        <td>{{ zone.school_tranzit }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="5">* Bus school term passes are only valid during school term dates. To find out the school term dates visit the <a href="http://www.minedu.govt.nz/theministry/educationinnewzealand/schooltermsandholidays.aspx" target="_blank">Ministry of Education website</a>.</td>
                </tr>
                <tr>
                    <td colspan="5"># Rail school term passes are available to full-time primary and secondary school students for travel between school and the station nearest their home.</td>
                </tr>
               
            </tbody>
            </table>


            <h3>Runcimans servces</h3>
            <table class="table">
            <tbody>
            <tr>
                <td class="col-md-10">Porirua/Papakowhai/Whitby to Hutt Valley Schools</td> 
                <td class="col-md-2">$320.00</td>
            </tr>
            <tr>
                <td>Petone and Lower Hutt to Upper Hutt Schools</td> 
                <td>$160.00</td>
            </tr>
            <tr>
                <td>Upper Hutt, Stokes Valley to Lower Hutt Schools</td> 
                <td>$160.00</td>
            </tr>
            <tr>
                <td>Stokes Valley, Upper Hutt to any Upper Hutt Schools</td> 
                <td>$115.00</td>
            </tr>
            <tr>
                <td>Runcimans Special School Service Fares - Child Single</td> 
                <td>$6.50</td>
            </tr>
            <tr>
                <td>Runcimans Special School Service Fares - Child Multi (per trip)</td> 
                <td>$4.98</td>
            </tr>
            </tbody>
            </table>
            
        </div>
    </div>
</div>


{% endblock %}